<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <!-- Promises always return two values 
    1. either the statement has resolved 
    2. either the statement/execution has been rejected -->

    <!-- <button onclick=showData()>show data</button> -->
    
    <script>
        function showData() {
            setTimeout(() => {
                console.log(1)
                document.write(1)

                setTimeout(() => {
                    console.log(2)
                    document.write(2)

                    setTimeout(() => {
                        console.log(3)
                        document.write(3)
                    }, 1000)
                }, 3000)
            }, 5000)
        }


        // creating a promise 

        // syntax - to create a promise 

        // const promise = new Promise((resolve, reject) => {})

        //this and then keyword

        const promise = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('Resolving async request..!!'), 2000
            })           
        })


        const promise2 = new Promise(function(resolve, error) {
            const x = 200;
            const y = "200";

            if(x==y){
                resolve("Succes");
            } else {
                error("Error");
            }
        });


// consuming of a promise is done by registering functions using .then and .catch
// use then method for the part which is fulfilling  the condition or resolving the output
//catch method is used for the rejected or erroe part of promise 
promise2.then(function () {
            console.log("Success, Both values matched");
        }).catch(function () {
            console.log("Error, values don't match");
        });

        promise.then((response) => {
                console.log(response)
            })


            promise2.then(function (succesMessage) {
                console.log(succesMessage);
            }) .catch( function(errorMessage) {
                console.log(errorMessage)
            })


            // Promise chaining - then method always returns a new promise 
            // we can chain promises with precise 
            //control over how and where errors are handled.



            //promise chaining 

            const wait = time => new Promise (
                res => setTimeout(() => res(), time)
            );

            wait(200) 

            .then(() => new Promise(res => res("Success")))

            .then(a => a)


            .then(b => console.log(b))

            .then(() => null)


            .then(c => console.log(c))


            .then(()=> {throw new Error("Succes");})


            .then (

            d => console.log(`d: ${d}`),

            e => console.log(e))



    </script>
</body>
</html>